name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        run: |-
          cd pipeline1 && docker build -t mayankjha-purdue/mgmt590-mayank:${{ github.sha }} .
          docker push mayankjha-purdue/mgmt590-mayank:${{ github.sha }} && cd ../

